version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - PGHOST=ep-divine-poetry-a5pb40al.us-east-2.aws.neon.tech
      - PGDATABASE=logeiqueDatabase
      - PGUSER=logeiqueDatabase_owner
      - PGPASSWORD=sAK67WLdNjBv
      - PGPORT=5432
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
