  # backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logeique-backend
  labels:
    app: logeique-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logeique-backend
  template:
    metadata:
      labels:
        app: logeique-backend
    spec:
      containers:
      - name: logeique-backend
        image: localhost/logeique-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: PGHOST
          value: 'ep-divine-poetry-a5pb40al.us-east-2.aws.neon.tech'
        - name: PGDATABASE
          value: 'logeiqueDatabase'
        - name: PGUSER
          value: 'logeiqueDatabase_owner'
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: logeique-backend-service
spec:
  selector:
    app: logeique-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
